# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Squid"
license = "MIT"
licenselink = "https://github.com/thenormalsquid/squid-theme/blob/master/LICENSE.md"
description = ""
homepage = ""
tags = ["responsive", "personal"]
features = ["responsive"]
min_version = "0.25.1"

[author]
  name = "Thien-Bach Huynh"
  homepage = "https://thenormalsquid.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
